# .github/release.yml
name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    name: "Release"
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Create Release
        id: create_release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          release_title: "What's Changed"
          changelog_file: "CHANGELOG.md"
          body: ${{ steps.generate_changelog.outputs.changelog }}
# changelog:
#   exclude:
#     labels:
#       - ignore-for-release
#     authors:
#       - octocat
#   categories:
#     - title: Breaking Changes 🛠
#       labels:
#         - Semver-Major
#         - breaking-change
#     - title: Exciting New Features 🎉
#       labels:
#         - Semver-Minor
#         - enhancement
#     - title: Other Changes
#       labels:
#         - "*"
